name: Assignment1 Deploy to ECR

on: 
  push:
    branches: [ development ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: assignment1-images-repo
        IMAGE_TAG: v0.1
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:Ass1-mysql-image-$IMAGE_TAG -f Dockerfile_mysql .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:Ass1webapp-$IMAGE_TAG .
        docker network create Ass1network
        docker run -d --name Ass1-mysql-container --network Ass1network -e MYSQL_ROOT_PASSWORD=Ass1Password $ECR_REGISTRY/$ECR_REPOSITORY:Ass1-mysql-image-$IMAGE_TAG
        docker run -d --name Ass1-webapp-container-blue --network Ass1network -p 8081:8080 \
          -e DBHOST=Ass1-mysql-container \
          -e DBPORT=3306 \
          -e DBUSER=root \
          -e DBPWD=Ass1Password \
          -e DBNAME=mydatabase \
          -e APP_COLOR=blue \
          $ECR_REGISTRY/$ECR_REPOSITORY:Ass1webapp-$IMAGE_TAG
        docker ps
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:Ass1-mysql-image-$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:Ass1webapp-$IMAGE_TAG
